--Scrip para a MPV - implantação da NF-e

--Operação 1
CREATE TABLE FATNFE (
    FAT_CODEMP  INTEGER,
    FAT_DTERES  DATE,
    FAT_NUMRES  INTEGER,
    FAT_SEQLIB  INTEGER,
    FAT_SEQFAT  INTEGER,
    OUT_CODEMP  INTEGER,
    OUT_DTEGER  DATE,
    OUT_NUMGER  INTEGER,
    DEV_CODEMP  INTEGER,
    DEV_DTERES  DATE,
    DEV_NUMRES  INTEGER,
    DEV_SEQLIB  INTEGER,
    DEV_SEQFAT  INTEGER,
    CODCLP      CHAR(1),
    CODGRU      CHAR(3),
    CODSUB      CHAR(4),
    CODPRO      CHAR(5),
    CODTAM      VARCHAR(10),
    CODCOR      VARCHAR(10),
    DESNFE      VARCHAR(70),
    NCMNFE      CHAR(30),
    SITNFE      CHAR(4),
    UNDNFE      CHAR(3),
    CFONFE      CHAR(10),
    QTPNFE      NUMERIC(15,4) DEFAULT 0,
    VLQNFE      NUMERIC(15,4) DEFAULT 0,
    TOTNFE      NUMERIC(15,2) DEFAULT 0,
    BASICM      NUMERIC(15,2) DEFAULT 0,
    TOTICM      NUMERIC(15,2) DEFAULT 0,
    TOTIPI      NUMERIC(15,2) DEFAULT 0,
    ICMNFE      NUMERIC(15,2) DEFAULT 0,
    IPINFE      NUMERIC(15,2) DEFAULT 0,
    NRONFE      INTEGER,
    ITENFE      CHAR(3),
    DEV_SEQDEV  INTEGER )
--

--Operação 1,5
alter table fincli add id_finuff integer;
alter table fincli add id_fincif integer;
--


--Operação 2
ALTER TABLE FATGER
ADD ID_FATGER INTEGER,
ADD QTIGE2 INTEGER,
ADD SEQNFE CHAR(44),
ADD DTENFE DATE,
ADD MODPFA VARCHAR(20),
ADD RECNFE CHAR(15),
ADD ARQNFE BLOB SUB_TYPE 0 SEGMENT SIZE 80,
ADD BAFCLI VARCHAR(20),
ADD CEFCLI VARCHAR(8),
ADD CIFCLI VARCHAR(20),
ADD CODTRA INTEGER,
ADD DOPNFE DATE,
ADD DTCNFE DATE,
ADD DTECAN DATE,
ADD DTECNE DATE,
ADD DTENPF DATE,
ADD ENFCLI VARCHAR(70),
ADD FLGSEG CHAR(3),
ADD HRCNFE CHAR(8),
ADD HRECAN CHAR(8),
ADD HRECNE CHAR(8),
ADD HRENFE CHAR(8),
ADD HREPNF CHAR(8),
ADD ID_ESTSIP INTEGER,
ADD ID_FINCIE INTEGER,
ADD ID_FINCIF INTEGER,
ADD ID_FINUFE INTEGER,
ADD ID_FINUFF INTEGER,
ADD ID_TRACIE INTEGER,
ADD ID_TRAUFE INTEGER,
ADD IMPNFE CHAR(3),
ADD LOTNFE INTEGER,
ADD NFECOF CHAR(2),
ADD NFEPIS CHAR(2),
ADD NRFCLI VARCHAR(10),
ADD NRONOT INTEGER,
ADD OB1CAN VARCHAR(80),
ADD OB1ENT VARCHAR(80),
ADD OB1SDA VARCHAR(80),
ADD OB2CAN VARCHAR(80),
ADD OB2ENT VARCHAR(80),
ADD OB2SDA VARCHAR(80),
ADD OB3CAN VARCHAR(80),
ADD OB3ENT VARCHAR(80),
ADD OB3SDA VARCHAR(80),
ADD OB4CAN VARCHAR(80),
ADD OB4ENT VARCHAR(80),
ADD OB4SDA VARCHAR(80),
ADD OB5CAN VARCHAR(80),
ADD OB5ENT VARCHAR(80),
ADD OB5SDA VARCHAR(80),
ADD QTDNOT INTEGER DEFAULT 0,
ADD QTIGE3 INTEGER DEFAULT 0,
ADD QTISGE INTEGER DEFAULT 0,
ADD RFFCLI VARCHAR(40),
ADD SEQFIN INTEGER,
ADD SEQINI INTEGER,
ADD SERNOT VARCHAR(10),
ADD SERSEL VARCHAR(10),
ADD TEFCLI VARCHAR(10),
ADD UFECOM CHAR(2),
ADD UFFCLI CHAR(2),
ADD USUCAN INTEGER,
ADD USUNFE INTEGER,
ADD PRONFE CHAR(15),
ADD DTEPNF DATE,
ADD RETNFE VARCHAR(100),
ADD ENVNFE CHAR(3),
ADD FLGNFE CHAR(3),
ADD DTECOM DATE,
ADD RTENFE VARCHAR(100),
ADD NFSCOM INTEGER,
ADD SEQCOM CHAR(44),
ADD PRCNFE CHAR(15),
ADD FLGREC CHAR(1),
ADD FLGAPR CHAR(1),
ADD FLGQTD CHAR(1);
--

--Operação 3
ALTER TABLE FATPED
ADD ARQNFE BLOB SUB_TYPE 0 SEGMENT SIZE 80,
ADD AVIDUP CHAR(3), 
ADD AVINOT CHAR(3), 
ADD CEFCLI CHAR(8), 
ADD DOPNFE DATE, 
ADD DSCFAT NUMERIC(15,2) DEFAULT 0, 
ADD DTCNFE DATE, 
ADD DTECAN DATE, 
ADD DTECNE DATE, 
ADD DTEDEV DATE, 
ADD DTENFE DATE,
ADD FLGANT CHAR(3),
ADD FLGSEG CHAR(3), 
ADD HRCNFE CHAR(8), 
ADD HRECAN CHAR(8), 
ADD HRECNE CHAR(8), 
ADD HREDEV CHAR(8), 
ADD HRENFE CHAR(8),
ADD ID_ESTSIP INTEGER, 
ADD ID_FATPED INTEGER,    --  verifcar com certeza esse campo NOT NULL, 
ADD ID_FINCIE INTEGER, 
ADD ID_FINCIF INTEGER, 
ADD ID_FINUFE INTEGER,
ADD ID_FINUFF INTEGER,
ADD ID_PEDCND INTEGER, 
ADD ID_TRACIE INTEGER, 
ADD ID_TRAUFE INTEGER, 
ADD LOTNFE INTEGER, 
ADD NFECOF CHAR(2), 
ADD NFEPIS CHAR(2), 
ADD NRONOT INTEGER, 
ADD OB1CAN VARCHAR(80), 
ADD OB1DES VARCHAR(80), 
ADD OB1DEV VARCHAR(80), 
ADD OB1ENT VARCHAR(80), 
ADD OB1SDA VARCHAR(80), 
ADD OB2CAN VARCHAR(80),
ADD OB2DES VARCHAR(80), 
ADD OB2DEV VARCHAR(80), 
ADD OB2ENT VARCHAR(80), 
ADD OB2SDA VARCHAR(80), 
ADD OB3CAN VARCHAR(80), 
ADD OB3DES VARCHAR(80), 
ADD OB3DEV VARCHAR(80), 
ADD OB3ENT VARCHAR(80), 
ADD OB3SDA VARCHAR(80), 
ADD OB4CAN VARCHAR(80), 
ADD OB4DES VARCHAR(80), 
ADD OB4DEV VARCHAR(80), 
ADD OB4ENT VARCHAR(80), 
ADD OB4SDA VARCHAR(80), 
ADD OB5CAN VARCHAR(80), 
ADD OB5DES VARCHAR(80), 
ADD OB5DEV VARCHAR(80), 
ADD OB5ENT VARCHAR(80), 
ADD OB5SDA VARCHAR(80),
ADD QTDNOT INTEGER DEFAULT 0,
ADD QTIPE2 INTEGER DEFAULT 0, 
ADD QTIPE4 INTEGER DEFAULT 0, 
ADD QTIPE5 INTEGER DEFAULT 0, 
ADD QTIPE6 INTEGER DEFAULT 0, 
ADD QTIPE7 INTEGER DEFAULT 0, 
ADD QTPSEL INTEGER DEFAULT 0, 
ADD RETNFE VARCHAR(100),
ADD SEQFIN INTEGER, 
ADD SEQINI INTEGER, 
ADD SERNOT VARCHAR(10),
ADD SERSEL VARCHAR(10), 
ADD TOTFRE NUMERIC(15,2) DEFAULT 0,
ADD USUCAN INTEGER,
ADD USUDEV INTEGER, 
ADD USUNFE INTEGER,
ADD FLGNFE CHAR(3),
ADD ENVNFE CHAR(3),
ADD TEFCLI VARCHAR(10),
ADD IMPNFE CHAR(3),
ADD ENFCLI VARCHAR(7),
ADD SEQNFE CHAR(44),
ADD RFFCLI VARCHAR(40),
ADD RECNFE CHAR(15),
ADD NRFCLI VARCHAR(10),
ADD PRONFE CHAR(15),
ADD BAFCLI VARCHAR(20),
ADD PRCNFE CHAR(15),
ADD CIFCLI VARCHAR(20),
ADD DTEPNF DATE,
ADD UFFCLI CHAR(2),
ADD HREPNF CHAR(8),
ADD MODFRT CHAR(16),
ADD FLGNOT CHAR(3),
ADD UFECOM CHAR(2),
ADD FLGREC CHAR(1),
ADD flgapr CHAR(1),
ADD flgqtd CHAR(1);
--ADD flgapr CHAR(1);
--

--Operação 4
ALTER TABLE FATDEV
ADD ARQNFE BLOB SUB_TYPE 0 SEGMENT SIZE 80,
ADD BAFCLI CHAR(20),
ADD CEFCLI VARCHAR(8),
ADD CIFCLI CHAR(20),
ADD CODTRA INTEGER,
ADD DOPNFE DATE,
ADD DTCNFE DATE,
ADD DTECNE DATE,
ADD DTENFE DATE,
ADD DTEPNF DATE,
ADD ENFCLI CHAR(70),
ADD ENVNFE CHAR(3),
ADD FLGNFE CHAR(3),
ADD FLGNOT CHAR(3),
ADD HRCNFE CHAR(8),
ADD HRECNE CHAR(8),
ADD HRENFE CHAR(8),
ADD HREPNF CHAR(8),
ADD ID_ESTSIP INTEGER,
ADD ID_FINCIE INTEGER,
ADD ID_FINCIF INTEGER,
ADD ID_FINUFE INTEGER,
ADD ID_FINUFF INTEGER,
ADD ID_TRACIE INTEGER,
ADD ID_TRAUFE INTEGER,
ADD IMPNFE CHAR(3),
ADD LOTNFE INTEGER,
ADD NFECOF CHAR(2),
ADD NFEPIS CHAR(2),
ADD NRFCLI CHAR(10),
ADD PRCNFE CHAR(15),
ADD PRONFE CHAR(15),
ADD RECNFE CHAR(15),
ADD RETNFE VARCHAR(100),
ADD RFFCLI CHAR(40),
ADD SEQNFE CHAR(44),
ADD TEFCLI VARCHAR(10),
ADD TRBCOF CHAR(3),
ADD TRBPIS CHAR(3),
ADD UFFCLI CHAR(2),
ADD USUNFE INTEGER,
add bascat numeric(15,2),
ADD TOTCAT NUMERIC(15,2);
--

--Operação 5
ALTER TABLE GEREMP ADD ID_FINCIE INTEGER;
ALTER TABLE GEREMP ADD ID_FINUFE INTEGER;
ALTER TABLE GEREMP ADD ID_FINPAI INTEGER;
ALTER TABLE GEREMP ADD IMUEMP CHAR(18);
ALTER TABLE GEREMP ADD FLGSEL CHAR(3);
alter table geremp ADD FLGNFE CHAR(3);
--

--ALTER TABLE GEREMP ADD CONSTRAINT FKGEREMP_FINCIE FOREIGN KEY (ID_FINCIE) REFERENCES FINCIE (ID_FINCIE);
--ALTER TABLE GEREMP ADD CONSTRAINT FKGEREMP_FINPAI FOREIGN KEY (ID_FINPAI) REFERENCES FINPAI (ID_FINPAI);
--ALTER TABLE GEREMP ADD CONSTRAINT FKGEREMP_FINUFE FOREIGN KEY (ID_FINUFE) REFERENCES FINUFE (ID_FINUFE);

--Operação 6
ALTER TABLE FATPE2
ADD TOTFRT NUMERIC (15,2),
ADD TOTSEG NUMERIC (15,2),
ADD TOTDES NUMERIC (15,2);
--

--Operação 7
ALTER TABLE FATGE2
ADD TOTFRT NUMERIC (15,2),
ADD TOTSEG NUMERIC (15,2),
ADD TOTDES NUMERIC (15,2);
--

--Operação 8
ALTER TABLE FATDV2
ADD TOTFRT NUMERIC (15,2),
ADD TOTSEG NUMERIC (15,2),
ADD TOTDES NUMERIC (15,2);

--Operação 8,5
--primeiro ajusta os campos necessários
alter table lojfat add flgnfe char(3);
alter table cmpnfs add flgnfe char(3);
--segundo acertar o código das triggers das tabela fatped, fatger e fatdev



-- Operação 8.8 - a MPV não tem esses campos
alter table fatger ADD ID_ESTDIP INTEGER;
--alter table fatger ADD ID_FINCIF INTEGER;
--alter table fatger add ID_FINUFF INTEGER;


--Operação 9
alter table geremp add nronfs integer
update geremp set qtdnfs = 0, nronfs = 0 where codemp = 1
update geremp set flgnfe = 'Sim' where codemp = 1




-- Fim do script


